# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            RTP SaberMetrics
tagline:          'Analyzing sports and stuff'
description:      'Analyze some sports data'
url:              http://ResearchTriangleAnalysts.github.io/SaberMetrics/index.html
baseurl:          /

author:
  name:           'Research Triangle Analysts'
  url:            https://twitter.com/rtpanalysts

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/ResearchTriangleAnalysts/SaberMetrics
